#!/bin/bash

#show server infos
echo "[1] NeSE BuildServer(16.04 x64)"
echo "[2] NeSE WorkServer (18.04 x64)"
echo "[3] NeSE MainServer (Centos6)"
echo "[4] Self process server(local)"
echo "[5] Self process server(remote)"
echo "[6] Self VMServer(1804)"
echo "[7] Self VMServer(1604)"
echo "[8] to be continue.."

#read user choice
read -p "Give me a choice: " SER_CHOICE
echo $SER_CHOICE

#perform login!
if [ $SER_CHOICE == "1" ];then 
scp -r -P622 root@124.16.75.161:$1 $2
fi 
if [ $SER_CHOICE == "3" ];then 
scp -r -P40010 root@124.16.75.161:$1 $2
fi
if [ $SER_CHOICE == "4" ];then
scp -r root@192.144.143.151:$1 $2
fi
if [ $SER_CHOICE == "5" ];then
scp -r -P27390 root@afang.xyz:$1 $2
fi 
if [ $SER_CHOICE == "6" ];then
scp -r root@192.168.220.128:$1 $2
fi
if [ $SER_CHOICE == "7" ];then
scp -r root@192.168.220.133:$1 $2
fi
